import glob

from pathlib import Path
import time

from maize.core.workflow import Workflow
from maize.core.graph import Graph
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage

from maize.steps.mai.docking.adv import AutoDockGPU
import numpy as np
from numpy.typing import NDArray
from maize.steps.mai.molecule import Gypsum, LoadMolecule

from maize.steps.mai.misc import ReInvent, ReinventEntry, ReinventExit, StripEpoch
from maize.steps.io import Void
from maize.utilities.chem import IsomerCollection
from maize.core.interface import Input, Output, Parameter, FileParameter
from maize.core.node import Node
from maize.steps.mai.cheminformatics import RMSD, ExtractScores, TagIndex, SortByTag, TagSorter, LogTags
from maize.utilities.io import setup_workflow
import pandas as pd
totalIsomerCollection: list[IsomerCollection] = []
# retu = flow.add(Return[list[IsomerCollection]])

# @expose_reinvent
class DockGPU_custom(Graph):
    """
    Facilitates docking simulations using Gypsum and AutoDockGPU, and saves the processed docking results.

    This class integrates a Gypsum module for molecular modifications, an AutoDockGPU docking engine
    for scoring, and a logger to save docking results into files. It is designed to process input molecules,
    apply filters and modifications, and ultimately save the docking results along with computed scores.
    The class allows detailed configurations such as number of molecular variants, pH range, thoroughness,
    parallel processing parameters, and docking-specific parameters.

    :ivar inp: Input molecules for docking simulations.
    :type inp: Input[list[str]]
    :ivar out_scores: Docking scores generated by the AutoDockGPU.
    :type out_scores: Output[NDArray[np.float32]]
    :ivar out: Docked molecules as collections of isomers.
    :type out: Output[list[IsomerCollection]]
    :ivar n_variants: Number of molecular variants to generate.
    :type n_variants: Parameter[int]
    :ivar ph_range: Range of pH levels to be applied in the simulation.
    :type ph_range: Parameter[tuple[float, float]]
    :ivar n_jobs: Number of parallel threads for processing.
    :type n_jobs: Parameter[int]
    :ivar thoroughness: Thoroughness of the molecular modifications and docking.
    :type thoroughness: Parameter[int]
    :ivar grid_file: File path to the grid file for docking configuration.
    :type grid_file: FileParameter[Path]
    :ivar heurmax: Maximum heuristics to apply during docking calculations.
    :type heurmax: Parameter[int]
    :ivar base_path: Base path for saving docking molecules and results.
    :type base_path: FileParameter[Path]
    """

    inp: Input[list[str]]
    out_scores: Output[NDArray[np.float32]] # docking scores
    out: Output[list[IsomerCollection]]  # all docked molecules
    
    # Gypsum
    n_variants: Parameter[int]
    ph_range: Parameter[tuple[float, float]]
    n_jobs: Parameter[int]
    thoroughness: Parameter[int]

    # ADGPU
    grid_file: FileParameter[Path]
    heurmax: Parameter[int]

    # Mol save location
    base_path: FileParameter[Path]

    def build(self) -> None:
        gyp = self.add(Gypsum)
        adg = self.add(AutoDockGPU)
        log = self.add(SaveLibraryEveryEpoch)
        gyp.use_filters.set(False)
        adg.scores_only.set(False)
        adg.strict.set(False)
        gyp.ph_range.set((6.5, 7.5))

        self.connect_all((gyp.out, adg.inp), (adg.out, log.inp))
        self.map(
            gyp.n_variants,
            gyp.ph_range,
            gyp.n_jobs,
            gyp.thoroughness,
            adg.grid_file,
            adg.heurmax,
            log.base_path,
        )
        self.inp = self.map_port(gyp.inp)
        self.out_scores = self.map_port(adg.out_scores)
        self.out = self.map_port(log.out)



def sdf_to_dataframe(sdf_file):
    suppl = Chem.SDMolSupplier(sdf_file)
    data = []

    for mol in suppl:
        if mol is not None:  # Ensure that the molecule is valid
            properties = mol.GetPropsAsDict()
            properties['Structure'] = Chem.MolToSmiles(mol)  # Convert to SMILES format
            data.append(properties)

    return pd.DataFrame(data)

class SDFToDataframe(Node):
    """Save a list of molecules to multiple SDF files."""

    inp: Input[list[IsomerCollection]] = Input()
    """Molecule library input"""
    # out: Output[list[IsomerCollection]] = Output()
    # """send out the Molecule library output, same as input"""
    base_path: FileParameter[Path] = FileParameter(exist_required=False)
    """Base output file path name without a suffix, i.e. /path/to/output"""



    def run(self) -> None:
        mols = self.inp.receive()
        base_path = self.base_path.value
        mainDataFrame = pd.DataFrame()
        fileName = str(base_path)+"*.sdf"
        for sdf in glob.glob(fileName):
            self.logger.debug(f"Processing {sdf}")
            df = sdf_to_dataframe(sdf)
            mainDataFrame = pd.concat([mainDataFrame, df])
            self.logger.debug(f"Processed {sdf}: Total isomers: {len(mainDataFrame)}, Isomers in this file {len(df)}")
        mainDataFrame.reset_index(drop=True, inplace=True)
        self.logger.debug(f" Total Isomer Count : {len(mainDataFrame)}")
        self.logger.debug(f" {(mainDataFrame.head(5))}")
        uniqueStructs = mainDataFrame['smiles'].unique()
        # minima = pd.DataFrame()
        minima = pd.DataFrame(columns=["smiles", "rmsd","energy","structure"])

        for smile in uniqueStructs:
            min_RMSD = mainDataFrame[mainDataFrame['smiles'] == smile]['rmsd'].min()
            energy = mainDataFrame[(mainDataFrame['smiles'] == smile) & (mainDataFrame['rmsd'] == min_RMSD)]['energy'].min()
            structure = mainDataFrame[(mainDataFrame['smiles'] == smile) & (mainDataFrame['rmsd'] == min_RMSD)]['Structure']

            minima.loc[len(minima)] = {'smiles':smile,'rmsd':min_RMSD, 'energy':energy, 'structure':structure}
        try:
            img = MolsToGridImage(
                Chem.MolFromSmiles(minima['smiles']),
                molsPerRow=10,
                maxMols=100,
                legends=[f"Energy: {row['energy']}" for _, row in minima.iterrows()],
                useSVG=False,
                returnPNG=True)
            with open(str(base_path)+".png", "wb") as f:
                f.write(img)
        except Exception as e:
            self.logger.error(f"Error drawing molecules: {e}")
        try:
            mainDataFrame.to_csv(str(base_path)+"_dump.csv")
            minima.to_csv(str(base_path)+"_minima.csv")
            self.logger.info(f"PFinished Processing - file should be at {str(base_path)+'.csv'}")
        except Exception as e:
            self.logger.error(f"Error saving Dataframe of molecules: {e}")



class SaveLibraryEveryEpoch(Node):
    """Save a list of molecules to multiple SDF files."""

    inp: Input[list[IsomerCollection]] = Input()
    """Molecule library input"""

    out: Output[list[IsomerCollection]] = Output()
    """send out the Molecule library output, same as input"""

    out2: Output[list[IsomerCollection]] = Output()
    """send same previous output the Molecule library output, same as input"""

    base_path: FileParameter[Path] = FileParameter(exist_required=False)
    """Base output file path name without a suffix, i.e. /path/to/output"""

    def run(self) -> None:
        mols = self.inp.receive()
        base = self.base_path.value
        for i, mol in enumerate(mols):
            file = base.with_name(f"{base.name}{i:04}.sdf")
            mol.to_sdf(file)
        try:
            self.logger.info(f"Saved molecules to {base}_*.sdf")
            self.out.send(mols)
            self.out.send(mols)
        except Exception as e:
            self.logger.error(f"Error saving molecules: {e}")


flow = Workflow(name="dock", level="debug", cleanup_temp=False)
flow.config.update(Path("/home/a/REINVENT4/ReinventStudies/configs/Maize/maize-mol2mol-config_2.toml"))
flow.config.scratch = (Path("/home/a/REINVENT4/ReinventStudies/scoringData/sampledDockingData/"))


rnvEntry = flow.add(ReinventEntry)
rnvExit = flow.add(ReinventExit)
stripEpoch = flow.add(StripEpoch, name="stripEpoch", loop=True)
void1 = flow.add(Void, name="void1")
embe = flow.add(Gypsum, loop=True)
dock = flow.add(AutoDockGPU, loop=True, cleanup_temp=False)
logger = flow.add(SaveLibraryEveryEpoch, name="logger", loop=True)
void2 = flow.add(Void, name="void2")
load = flow.add(LoadMolecule)
rmsd = flow.add(RMSD, loop=True)
logt = flow.add(LogTags, loop=True)
toPandas = flow.add(SDFToDataframe, loop=True)
# void3 = flow.add(Void, name="void3")

flow.combine_parameters(
    rnvEntry.data,
    name="inp")

flow.combine_parameters(
    rnvExit.data,
    name="out")

flow.connect_all(
    (rnvEntry.out, embe.inp),
    (rnvEntry.out_metadata, stripEpoch.inp),
    (stripEpoch.out, void1.inp),
    # (stripEpoch.out, logger.inp_epoch),
)
flow.connect_all(
    (embe.out, dock.inp),
    # (dock.out, rnvExit.inp)
    (dock.out_scores, void2.inp),
    (dock.out, rmsd.inp),
    (load.out, rmsd.inp_ref),
)

flow.connect_all(
    (rmsd.out, logt.inp),
    (logt.out, logger.inp),
    (logger.out2, toPandas.inp),
    # (logger.out2, void3.inp),
    (logger.out, rnvExit.inp),
)

rnvEntry.data.set(flow.config.scratch / "input.json")
rnvExit.data.set(flow.config.scratch / "output.json")

embe.use_filters.set(False)
embe.n_variants.set(10)
embe.ph_range.set((6.5, 7.5))

dock.nrun.set(50)
dock.population_size.set(300)
dock.lsit.set(600)
dock.grid_file.set(Path("/home/a/REINVENT4/ReinventStudies/mols/Rad51/maps/rad51_receptor.maps.fld"))
dock.constraints.set(False)
# flow.inp = flow.map_port(rnvEntry.data)
# flow.out = flow.map_port(rnvExit.data)

# Reference ligand for RMSD calculation
load.path.set(Path("/home/a/REINVENT4/ReinventStudies/mols/Rad51/Cam833HMdsRad51Docked_Cam833-Acid_3.sdf"))

# Log the "rmsd" tag
logt.tag.set("rmsd")

runName = "justmol2mol_4_compounds_Mols"
scratchLocation =f"/home/a/REINVENT4/ReinventStudies/scoringData/sampledDockingData/{runName}"

logger.base_path.set(Path(scratchLocation))

toPandas.base_path.set(Path(scratchLocation))

ts = time.strftime("%B_%d-%H%M%S")


for i in flow.config.nodes: 
    print(i)

flow.check()
flow.visualize()



setup_workflow(flow)
