# Test configuration for maize

# Various options for general configuration
scratch = "./temp2/"
packages = [
    "maize.steps.mai",
    "maize.steps.mai.misc.reinvententry",
    "maize.steps.mai.misc.reinventexit",
    "maize.graphs.mai",
    "maize.graphs.mai.dock",
]

# Default batch system options for job scheduling
[batch]
system = "local"
walltime = "24:00:00"

# Autodock Vina configuration settings
[vina]
commands.vina = "./autodock_vina_1_1_2_linux_x86/bin/vina"

# Vina scoring configuration settings
[vinascore]
commands.vina = "./autodock_vina_1_1_2_linux_x86/bin/vina"

# Gypsum-DL configuration settings
[gypsum]
scripts.gypsum.interpreter = "conda run -n gypsum_dl_env "
scripts.gypsum.location = "/home/a/miniconda3/envs/gypsum_dl_env/bin/run-gypsum-dl"


[reinvent]
scripts.reinvent.interpreter = "/home/a/miniconda3/envs/reinvent4/bin/python"
scripts.reinvent.location = "/home/a/miniconda3/envs/reinvent4/bin/reinvent"

[reinvententry]
scripts.reinvent.interpreter = "/home/a/miniconda3/envs/reinvent4/bin/python"
scripts.reinvent.location = "/home/a/miniconda3/envs/reinvent4/bin/reinvent"

[reinventexit]
scripts.reinvent.interpreter = "/home/a/miniconda3/envs/reinvent4/bin/python"
scripts.reinvent.location = "/home/a/miniconda3/envs/reinvent4/bin/reinvent"


# AutoDock-GPU configuration settings
[autodockgpu]
python = "/home/a/miniconda3/envs/maize-dev/bin/python"
modules = ["CUDA", "GCC", "meeko"]
commands.autodock_gpu = "/home/a/REINVENT4/ReinventStudies/adgpu-v1.6_linux_x64_cuda12_128wi"

[boltz]
scripts.boltz.interpreter = "conda run -n boltz "
scripts.boltz.location = "/home/a/miniconda3/envs/boltz/bin/boltz"

[preparepdbqt]
commands.prepare_receptor = "/home/a/miniconda3/envs/adt/bin/prepare_receptor4.py"
scripts.prepare_receptor.interpreter = "/home/a/miniconda3/envs/adt/bin/python"
scripts.prepare_receptor.location = "/home/a/miniconda3/envs/adt/bin/prepare_receptor4.py"

